### ISSUE TITLE
Recovery of FasterLog crashes when log is aggressively truncated 

### ISSUE THREAD

**Issue by tli2** [microsoft/FASTER#191]
In FasterLogSample, the reader truncates the log after reading it. Normally, reading rate is smaller than append rate and everything is fine. In cases where reading rate and append rate is similar, and the program is stopped ungracefully, the recovered begin address can be close to the recovered FlushedUntil address, and the assertion on  Recovery.cs:427 fails as the head of page is behind begin address already.

To reproduce this, one can artificially throttle the writer performance (e.g. sleep 1ms after each write), use a large page size, and randomly kill the program while running before recovering. 

Not sure what the best fix is, one easy fix is to truncate only up to the nearest page boundary, or we can remove the assert (not sure if the assert is guarding against some other anomaly)

**Comment by badrishc** [comment]
Fixed in master.

**Comment by itn3000** [comment]
I've got error about truncating data too.
I truncated data until last 4096 bytes, and scan log then I got the following error.
This is not fixed even if using master branch.

```
Unhandled exception. System.Exception: Invalid length of record found: 1128481603, skipping page
   at FASTER.core.FasterLogScanIterator.GetNextInternal(Int64& physicalAddress, Int32& entryLength, Boolean& epochTaken) in G:\src\gitrepos\Microsoft.FASTER\cs\src\core\Index\FasterLog\FasterLogIterator.cs:line 445
   at FASTER.core.FasterLogScanIterator.GetNext(Byte[]& entry, Int32& entryLength) in G:\src\gitrepos\Microsoft.FASTER\cs\src\core\Index\FasterLog\FasterLogIterator.cs:line 182
   at FASTER.core.FasterLogScanIterator.GetAsyncEnumerable(CancellationToken token)+MoveNext() in G:\src\gitrepos\Microsoft.FASTER\cs\src\core\Index\FasterLog\FasterLogIterator.cs:line 108
   at FASTER.core.FasterLogScanIterator.GetAsyncEnumerable(CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at FasterLogTruncateTest.DoTest() in G:\src\gitrepos\dotnet-sandbox\fasterlabs\FasterLogTruncateTest.cs:line 44
   at FasterLogTruncateTest.DoTest() in G:\src\gitrepos\dotnet-sandbox\fasterlabs\FasterLogTruncateTest.cs:line 44
   at fasterlabs.Program.Main(String[] args) in G:\src\gitrepos\dotnet-sandbox\fasterlabs\Program.cs:line 185
   at fasterlabs.Program.<Main>(String[] args)
```

test code is https://gist.github.com/itn3000/a11043a6bcef19d267b90bb8431cd3e3

**Comment by badrishc** [comment]
@itn3000 - your issue is slightly different. You are supposed to use TruncateUntil to move the begin address to only valid addresses on the log, where a record starts. In your case, you have moved the iterator to (current - 4096). Each entry on the log takes up (64 + 4) bytes, or (64 + 12) if you checksums. Thus, (current - 4096) is an invalid location to truncate until. During resume, therefore, we will look for a valid record at that address and fail because it is not the starting position for any record.

All, there are two possible API changes we could do to prevent users from truncating badly.

* Move Truncate to a method on the Scan iterator, without any argument. The semantics would be to truncate until the iterator's current address. Since the iterator is usually at a good position (assuming it was initialized correctly), the truncate will not cause the log to start at an incorrect address.
* Change TruncateUntil on FasterLog, so that it only accepts addresses that are aligned to page boundaries, which are guaranteed to be good truncation points.
* We could retain the current TruncateUntil with a caveat that user is responsible, plus add a safer version: TruncateUntilPage(long page).

Thoughts?

**Comment by hiteshmadan** [comment]
Moving truncate to be an iterator method will reduce usability hugely - in my case we feed the read entries to a set of parallel workers and only truncate when the processing is done, thus cant decide to truncate at the time of read.

Accepting aligned is a good idea but it still makes it easy to fumble up truncation - for instance, should the log reader use the iterator.CurrentAddress as the truncation marker, or next address (both of which are aligned i guess?)

How does it sound to also return an explicit "long truncateAddress" value with each GetNext?

bool found = GetNext(out byte[] entry, out long truncateAddress) ?

**Comment by badrishc** [comment]
Yes, we will need to continue to support `TruncateUntil` with an arbitrary address as input, because the user might squirrel away a valid address from an earlier iteration/enqueue operation, and then later wish to call `TruncateUntil` until that specific address.

`GetNext` does not need to return a truncate address - users can save either `iter.CurrentAddress` or `iter.NextAddress` at any point in time, as per their requirement. Both addresses can always be used as valid truncate addresses any time in future.

We can also add a `TruncateUntilPageStart(long address)` that will truncate until the _start_ of the page corresponding to the provided logical address. This API is safer to use with any address, as it will truncate only until the start of the corresponding page.
