### ISSUE TITLE
Explanation on some of the setting params

### ISSUE THREAD

**Issue by dangershony** [microsoft/FASTER#245]
```
        /// <summary>
        /// Size of a segment (group of pages), in bits
        /// </summary>
        public int PageSizeBits = 25;

        /// <summary>
        /// Size of a segment (group of pages), in bits
        /// </summary>
        public int SegmentSizeBits = 30;

        /// <summary>
        /// Total size of in-memory part of log, in bits
        /// </summary>
        public int MemorySizeBits = 34;

        /// <summary>
        /// Fraction of log marked as mutable (in-place updates)
        /// </summary>
        public double MutableFraction = 0.9;

```

Can any of this values change after the db was created?
Perhaps I can get some more information on each of this params?

**Comment by ThiagoT1** [comment]
This page has some info:
https://microsoft.github.io/FASTER/tuning/Log.html

# Configuring the Hybrid Log

Recall that FASTER consists of the hash index that connects to a hybrid log spanning storage and main 
memory. The hybrid log may be configured using the `LogSettings` input to the FasterKV constructor.

```cs
var fht = new FasterKV<...>(1L << 20, new Funcs(), new LogSettings { ... }, ...);
```

The following log settings are available for configuration:

* `LogDevice`: This is an instance of the storage interface (device/path/file) that will be used for the
main log. It is a class that implements the `IDevice` interface. FASTER provides several device implementations 
out of the box, such as `LocalStorageDevice` and `ManagedLocalStorageDevice` for local (or attached) storage.
You can use our extension method to easily create an instance of a local device:
    ```cs
    var log = Devices.CreateLogDevice(Path.GetTempPath() + "hlog.log");
    ```
    When using FASTER in memory, you can set the device to a null device (`NullDevice`) by providing an empty
    string as parameter to the method above.

* `ObjectLogDevice`: If you are using C# class objects as FASTER keys and/or values, you need to also
provide storage for the object log, similar to the main log described above.

* `PageSizeBits`: This field (P) is used to indicate the size of each page. It is provided in terms of the number
of bits. You get the actual size of the page by a simple computation of two raised to the power of the number
specified (2<sup>P</sup>). For example, when `PageSizeBits` P is set to 12, it represents pages of size 4KB 
(since 2<sup>P</sup> = 2<sup>10</sup> = 4096 = 4KB). Generally you should not need to adjust page size from its
default value of 25 (= 32MB).

* `MemorySizeBits`: This field (M) indicates the total size of memory used by the log. As before, for a setting
of M, 2<sup>M</sup> is the number of bytes used totally by the log. Since each page is of size 2<sup>P</sup>, the 
number of pages in memory is simply 2<sup>M-P</sup>. FASTER requires at least 16 pages in memory, so M should be 
set to at least P+4.

* `MutableFraction`: This field (F) indicates the fraction of the memory that will be treated as _mutable_, i.e.,
updates are performed in-place instead of creating a new version on the tail of the log. A value of 0.9 (the
default) indicates that 90% of memory will be mutable.

* `SegmentSize`: On disk, the data is written to files in coarse-grained chunks called _segments_. We can size 
each chunk independently of pages, as one segment typically consists of many pages. For instance, if we want
each file on disk to be 1GB (the default), we can set `SegmentSizeBits` S to 30, since 2<sup>30</sup> = 1GB.

* `CopyReadsToTail`: This boolean setting indicates whether reads should be copied to the tail of the log. This
is useful when reads are infrequent, but will be followed by an update, or subsequent reads.

* `ReadCache`: This setting is used to enable our new feature, a separate read cache. If reads are
frequent, we recommend instead the read cache instead of `CopyReadsToTail`, as the latter can inflate
log growth unnecessarily.

**Comment by badrishc** [comment]
Thanks @ThiagoT1. @dangershony, these cannot be changed during runtime.

**Comment by dangershony** [comment]
If I want to reduce to minimum the amount of memory FASTER takes I assume then I need to make `PageSizeBits` smaller because `MemorySizeBits` has to be P + 4.

If I put a value of `PageSizeBits=12` and `MemorySizeBits=16`  is that acceptable?
I did notice that when I do that and let the program run after a few gb of data the recovery (after shutdown and startup from checkpoint) fails to load data that I expect to be in disk.

Is there a minimum number for  `PageSizeBits`?
Also I noticed the FASTER is very memory hungry,

**Comment by ThiagoT1** [comment]
It would be helpful if you could present a minimal repro.

Despite #238, this code is working ok, including recoveries:
https://github.com/ThiagoT1/FasterDictionary/tree/unsafe-0.0.3-fastread?files=1

Whats "mode" are you using (fixed length, unsafe var length, serializer / obj log)?

**Comment by dangershony** [comment]
The impl is here (I am attempting to use FASTER as a k/v for the consensus db of a blockchain project)

https://github.com/block-core/blockcore/blob/0a6c8c083fac03c1c3b43ee5ebff7904a1641b9f/src/Stratis.Bitcoin.Features.Consensus/CoinViews/Coindb.cs

You can see the FASTER setup in the code

**Comment by ThiagoT1** [comment]
From my experience, ObjLog does not seem to honor the MemorySizeBits setting, at least by eyeballing the process RAM consumption (vs unsafe var length strategy).

Maybe when using serializers there's too much memory overhead and the dynamically allocated portion of the heap starts to dominate.

I also noticed there's a lot of other thing going on on that code.

I suggest:
1) Create a clear repro of the recovery failure
2) Do some Heap snapshots on Visual Studio, or the good old windbg analysis

You could also consider using the FasterDictionary repo. I think the business code gets a lot cleaner once all things FASTER get wrapped away. Please note the branch I referred to uses the unsafe strategy, and locally references a clone of FASTER master branch.

**Comment by badrishc** [comment]
Faster is designed to use constrained memory. It's actually simple. With object log, the memory size refers to the size of the main log, which holds 24 byes per record if keys and values are pointers (objects). Given a memory size, you can thus compute the number of key and value objects in memory, if you know the sizes of your objects, you can compute the memory footprint.

**Comment by ThiagoT1** [comment]
In that context, when would objects be evicted from memory?
Would it be when the main log entries spill to disk?

**Comment by badrishc** [comment]
Correct, when the main log goes to disk, the corresponding objects do so as well.

**Comment by dangershony** [comment]
I suspect there is a memory leak, when node runs for while I get memory consumption go to 20gb and more, I can try to provide a play project to reproduce this (or one can easy reproduce this by running the daemon on the link I provided above)

**Comment by dangershony** [comment]
It might very well be that the way I configured faster is wrong and maybe I messed up the `functions` impl.
What is the lowest I can set for the `PageSizeBits`?

**Comment by badrishc** [comment]
We can look into this and fix. How do we repro using the link above, can you share details?

**Comment by badrishc** [comment]
> It might very well be that the way I configured faster is wrong and maybe I messed up the `functions` impl.
> What is the lowest I can set for the `PageSizeBits`?

A page can be sized as low as 512 bytes (PageSizeBits = 9). If your keys or values are struct types, they need to fit on one page.

Assuming both keys and values are classes, this above setting will store approximately 512/24 entries per page.

This is very tight. I would suggest a larger page size of your memory availability can afford it, e.g., set it to 15 or 20 or 30. There is a performance tradeoff.

Memory can be around 5-10 bits larger, so there are approximately 32 to 1024 pages in memory.

You can compute the total object pointers on memory based on the above.

**Comment by dangershony** [comment]
Thanks for the explanation, I assume the memory will grow to a certain point and after that data will spill to disk, so I don't expect to see it grow to 20GB as I observed.

My keys and values are byte[], key is array of 33 byte in size (1 byte for table and 32 byte for the key, the size of a uint256, value can be bigger up to 520 bytes. 

Sure I will provide detailed explanation on how to repro once I find the time.

**Comment by badrishc** [comment]
Ok. I assume you using actual byte arrays as key and value, and not the inline "varlen struct" supported by FASTER?

Note that the latter are more efficient, but a bit harder to use. If efficiency becomes a primary concern, we can discuss moving over to using that.

**Comment by badrishc** [comment]
Closing, assuming your memory issue is resolved. If not, feel free to reopen with a repro.

**Comment by dangershony** [comment]
I didn't have time to go deeper in to this sorry, I don't think it's resolved but I will check again when I have time and reopen with a proper way to reproduce this.
For now I defaulted to using leveldb with bindings (and it works very well, if I can replicate the same capabilities of leveldb with faster this will be magnificent as currently there is no proper k/v native c# solution)

**Comment by badrishc** [comment]
If you think LevelDB works well, then you will be amazed at FASTER's performance, once things are configured correctly. With any LSM structure such as LevelDB, you are paying a huge cost to keep things sorted by key. The main benefit of such an organization is to enable fast range searches by key range. If you need that functionality, then sure, go for it and FASTER is not a fit for your use case. But if you are looking for point lookups and updates (and read-modify-write) then nothing can beat FASTER in terms of performance. Otherwise, you are paying for heavy write amplification, high access cost, high tail latency, etc.

For your memory issue, i suspect the hash table is either sized incorrectly, or is growing large due to overflow buckets. This is easily fixable by controlling the hash bits. Is the sample application you contributed [here](https://github.com/microsoft/FASTER/tree/master/cs/playground/ClassRecoveryDurablity) a good fit for your use case? Will it demonstrate the issue u are running into, if allowed to run for long?

Thanks!
