### ISSUE TITLE
[C++] Concurrent in-memory benchmark on Linux

### ISSUE THREAD

**Issue by prashantpandey** [microsoft/FASTER#556]
Hi,

I am trying to get this concurrent in-memory benchmark work. It works with a single thread but queries fail when I use multiple threads. Any help is appreciated. 

The inserts happen in `do_inserts`  function concurrently. Queries follow the inserts, in `do_queries`.

Code:
```
#include <time.h>
#include <thread>
#include <immintrin.h>
#include <tmmintrin.h>
#include <openssl/rand.h>
#include <unistd.h>
#include <chrono>
#include <random>
#include <algorithm>

#include "core/faster.h"
#include "device/null_disk.h"

using namespace std::chrono;
using namespace FASTER::core;

//vectors of key/value pairs in the table and not in the table
std::vector<std::pair<uint64_t, uint64_t>> in_table, not_in_table;

/// This benchmark stores 8-byte keys in key-value store.
class Key {
 public:
  Key(uint64_t key)
    : key_{ key } {
  }

  /// Methods and operators required by the (implicit) interface:
  inline static constexpr uint32_t size() {
    return static_cast<uint32_t>(sizeof(Key));
  }
  inline KeyHash GetHash() const {
    return KeyHash{ Utility::GetHashCode(key_) };
  }

  /// Comparison operators.
  inline bool operator==(const Key& other) const {
    return key_ == other.key_;
  }
  inline bool operator!=(const Key& other) const {
    return key_ != other.key_;
  }

 private:
  uint64_t key_;
};

/// This benchmark stores an 8-byte value in the key-value store.
class Value {
 public:
  Value()
    : value_{ 0 } {
  }

  Value(const Value& other)
    : value_{ other.value_ } {
  }

  Value(uint64_t value)
    : value_{ value } {
  }

  inline static constexpr uint32_t size() {
    return static_cast<uint32_t>(sizeof(Value));
  }

  friend class ReadContext;
  friend class UpsertContext;
  friend class RmwContext;

 private:
  union {
    uint64_t value_;
    std::atomic<uint64_t> atomic_value_;
  };
};

/// Class passed to store_t::Read().
class ReadContext : public IAsyncContext {
 public:
  typedef Key key_t;
  typedef Value value_t;

  ReadContext(uint64_t key)
    : key_{ key } {
  }

  /// Copy (and deep-copy) constructor.
  ReadContext(const ReadContext& other)
    : key_{ other.key_ } {
  }

  /// The implicit and explicit interfaces require a key() accessor.
  inline const Key& key() const {
    return key_;
  }

  // For this benchmark, we don't copy out, so these are no-ops.
  inline void Get(const value_t& value) { }
  inline void GetAtomic(const value_t& value) { }

 protected:
  /// The explicit interface requires a DeepCopy_Internal() implementation.
  Status DeepCopy_Internal(IAsyncContext*& context_copy) {
    return IAsyncContext::DeepCopy_Internal(*this, context_copy);
  }

 private:
  Key key_;
};

/// Class passed to store_t::Upsert().
class UpsertContext : public IAsyncContext {
 public:
  typedef Key key_t;
  typedef Value value_t;

  UpsertContext(uint64_t key, uint64_t input)
    : key_{ key }
    , input_{ input } {
  }

  /// Copy (and deep-copy) constructor.
  UpsertContext(const UpsertContext& other)
    : key_{ other.key_ }
    , input_{ other.input_ } {
  }

  /// The implicit and explicit interfaces require a key() accessor.
  inline const Key& key() const {
    return key_;
  }
  inline static constexpr uint32_t value_size() {
    return sizeof(value_t);
  }

  /// Non-atomic and atomic Put() methods.
  inline void Put(value_t& value) {
    value.value_ = input_;
  }
  inline bool PutAtomic(value_t& value) {
    value.atomic_value_.store(input_);
    return true;
  }

 protected:
  /// The explicit interface requires a DeepCopy_Internal() implementation.
  Status DeepCopy_Internal(IAsyncContext*& context_copy) {
    return IAsyncContext::DeepCopy_Internal(*this, context_copy);
  }

 private:
  Key key_;
  uint64_t input_;
};

/// Context to delete a key when unit testing.
class DeleteContext : public IAsyncContext {
 private:
  Key key_;

 public:
  typedef Key key_t;
  typedef Value value_t;

  explicit DeleteContext(const Key& key)
    : key_{ key }
  {}

  inline const Key& key() const {
    return key_;
  }

  inline static constexpr uint32_t value_size() {
    return Value::size();
  }

 protected:
  /// The explicit interface requires a DeepCopy_Internal() implementation.
  Status DeepCopy_Internal(IAsyncContext*& context_copy) {
    return IAsyncContext::DeepCopy_Internal(*this, context_copy);
  }
};



/// Key-value store, specialized to our key and value types.
using store_t = FasterKv<Key, Value, FASTER::device::NullDisk>;

uint64_t ct;

double elapsed(high_resolution_clock::time_point t1, high_resolution_clock::time_point t2) {
	return (duration_cast<duration<double>>(t2 - t1)).count();
}

void do_inserts(std::vector<std::pair<uint64_t, uint64_t>>& v, uint64_t start, uint64_t n, store_t *table) {
  auto callback = [](IAsyncContext* ctxt, Status result) {
    assert(result == Status::Ok);
  };

  table->StartSession();
  for(uint64_t i = start; i < start + n; ++i) {
    UpsertContext context{ v[i].first, v[i].second };
    table->Upsert(context, callback, 1);
  }
  table->CompletePending(true);
  table->StopSession();
}

void do_queries(std::vector<std::pair<uint64_t, uint64_t>>& v, uint64_t start, uint64_t n, bool positive, store_t *table) {
  auto callback = [](IAsyncContext* ctxt, Status result) {
    assert(result == Status::Ok);
  };
  table->StartSession();
  for(uint64_t i = start; i < start + n; ++i) {
    ReadContext context{ v[i].first };
    Status result = table->Read(context, callback, 1);
    if((result == Status::Ok) != positive) {
	    ct++;
	    if(positive)
		    printf("False negative query\n");
	    else
		    printf("False positive query\n");
	    exit(0);
    }
  }
  table->StopSession();
}

void do_removals(std::vector<std::pair<uint64_t, uint64_t>>& v, uint64_t start, uint64_t n, store_t *table) {
	auto callback = [](IAsyncContext* ctxt, Status result) {
		assert(result == Status::Ok);
	};
  table->StartSession();
	for(uint64_t i = start; i < start + n; ++i) {
		DeleteContext context{ v[i].first };
		Status result = table->Delete(context, callback, 1);
		if (result != Status::Ok) {
			printf("Failed delete\n");
			exit(0);
		}
	}
  table->CompletePending(true);
  table->StopSession();
}

//void do_mixed(std::vector<std::pair<uint64_t, uint64_t>>& v, uint64_t start, uint64_t n, store_t *table) {
	
	//for(uint64_t i = start; i < start + n; ++i)
		//if(table.contains(v[i].first)) {
			
			//table.erase(v[i].first);
		//} else table.insert(v[i].first, v[i].second);
//}

int main (int argc, char** argv) {
	if (argc != 3) {
		fprintf(stderr, "Specify the log of the number of slots in the table and the number of threads to use.\n");
		exit(1);
	}

	uint64_t tbits = atoi(argv[1]);
	uint64_t threads = atoi(argv[2]);
	uint64_t N = (1ULL << tbits) * 0.95;
	
  	store_t table { (1ULL << tbits), 17179869184, "" };

	srand(time(NULL));

	//Generating vectors of size N for data contained and not contained in the tablea
	uint64_t *vals = (uint64_t*)malloc(N * 2 * sizeof(uint64_t));
	RAND_bytes((unsigned char *)vals, sizeof(*vals) * N * 2);
	uint64_t *other_vals = (uint64_t*)malloc(N * 2 * sizeof(uint64_t));
	RAND_bytes((unsigned char *)other_vals, sizeof(*other_vals) * N * 2);
	for (uint64_t i = 0; i < N * 2; i += 2) {
		in_table.push_back({vals[i], vals[i + 1]});
		not_in_table.push_back({other_vals[i], other_vals[i + 1]});
	}

	printf("INSERTIONS\n");

	uint64_t splits = 19;

	N -= N % splits;
	while(in_table.size() % (2 * splits * threads)) {
		in_table.pop_back();
		not_in_table.pop_back();
	}

	uint64_t size = N / splits / threads;
	ct = 0;

//	exit(0);

	high_resolution_clock::time_point t1, t2;

	t1 = high_resolution_clock::now();

	std::vector<std::thread> thread_list;
	for(uint64_t i = 0; i < splits; ++i) {
		
		//t1 = high_resolution_clock::now();
		
		for(uint64_t j = 0; j < threads; j++)
			thread_list.emplace_back(do_inserts, std::ref(in_table), (i * threads + j) * size, size, &table);
		for(uint64_t j = 0; j < threads; j++)
			thread_list[j].join();

		//t2 = high_resolution_clock::now();

		//printf("%f\n", size * threads / elapsed(t1, t2));
		thread_list.clear();
	}

	t2 = high_resolution_clock::now();
	printf("%f\n", N / elapsed(t1, t2));
	
	printf("Percent of failed inserts: %f\n", ((double)ct) / N);
	printf("Total inserts: %ld\n", N);

//	exit(0);

	printf("\nQUERIES\n");

	std::mt19937 g(__builtin_ia32_rdtsc());
	std::shuffle(in_table.begin(), in_table.end(), g);

//	exit(0);

	uint64_t val;
	t1 = high_resolution_clock::now();

	ct = 0;

	for(uint64_t i = 0; i < threads; ++i)
		thread_list.emplace_back(do_queries, std::ref(not_in_table), i * N / threads, N / threads, false, &table);
	for(uint64_t i = 0; i < threads; ++i)
		thread_list[i].join();
	
	t2 = high_resolution_clock::now();
	printf("Negative queries: %f /sec\n", N / elapsed(t1, t2));
	printf("Error rate: %f\n", ((double)ct) / N);	
	thread_list.clear();

//	exit(0);

	t1 = high_resolution_clock::now();
		
	ct = 0;

	for(uint64_t i = 0; i < threads; ++i)
		thread_list.emplace_back(do_queries, std::ref(in_table), i * N / threads, N / threads, true, &table);
	for(uint64_t i = 0; i < threads; ++i)
		thread_list[i].join();

	t2 = high_resolution_clock::now();
	printf("Positive queries: %f /sec\n", N / elapsed(t1, t2));
	printf("Error rate: %f\n", ((double)ct) / N);
	thread_list.clear();

//	exit(0);

	printf("\nREMOVALS\n");

	std::vector<std::pair<uint64_t, uint64_t>> removed, non_removed;

	for(uint64_t i = 0; i < N / 2; ++i) removed.push_back(in_table[i]);
	for(uint64_t i = N / 2; i < N; ++i) non_removed.push_back(in_table[i]);

	shuffle(removed.begin(), removed.end(), g);
	shuffle(non_removed.begin(), non_removed.end(), g);

	t1 = high_resolution_clock::now();
	
	ct = 0;

	for(uint64_t i = 0; i < threads; ++i)
		thread_list.emplace_back(do_removals, std::ref(removed), i * N / 2 / threads, N / 2 / threads, &table);
	for(uint64_t i = 0; i < threads; ++i)
		thread_list[i].join();
	
	t2 = high_resolution_clock::now();
	printf("Removals: %f /sec\n", (N / 2) / elapsed(t1, t2));
	printf("Number of failed removals: %ld\n", ct);
	printf("Percent of failed removals: %f\n", ((double)ct) / (N / 2));
	thread_list.clear();

	shuffle(removed.begin(), removed.end(), g);

	t1 = high_resolution_clock::now();

	ct = 0;

	for(uint64_t i = 0; i < threads; ++i)
		thread_list.emplace_back(do_queries, std::ref(removed), i * N / 2 / threads, N / 2 / threads, false, &table);
	for(uint64_t i = 0; i < threads; ++i)
		thread_list[i].join();

	t2 = high_resolution_clock::now();
	printf("Negative queries after removals: %f /sec\n", N / elapsed(t1, t2));
	printf("Error rate: %f\n", ((double)ct) / (N / 2));
	thread_list.clear();

	t1 = high_resolution_clock::now();
		
	ct = 0;

	for(uint64_t i = 0; i < threads; ++i)
		thread_list.emplace_back(do_queries, std::ref(non_removed), i * N / 2 / threads, N / 2 / threads, true, &table);
	for(uint64_t i = 0; i < threads; ++i)
		thread_list[i].join();

	t2 = high_resolution_clock::now();
	printf("Positive queries after removals: %f /sec\n", N / elapsed(t1, t2));
	printf("Error rate: %f\n", ct * 2 / (double)N);
	thread_list.clear();
	
/*
	printf("\nMIXED WORKLOAD, HIGH LOAD FACTOR\n");
	
	for(uint64_t i = 0; i < N; ++i) in_table.push_back(not_in_table[i]);

	shuffle(in_table.begin(), in_table.end(), g);

	t1 = high_resolution_clock::now();

	for(uint64_t i = 0; i < threads; ++i)
		thread_list.emplace_back(do_mixed, std::ref(in_table), i * 2 * N / threads, 2 * N / threads);
	for(uint64_t i = 0; i < threads; ++i)
		thread_list[i].join();

	t2 = high_resolution_clock::now();
	printf("Mixed operations at high load factor: %f /sec\n", 4 * N / elapsed(t1, t2));
	thread_list.clear();*/
}
```

Output:
```
$ numactl -N 1 -m 1 ./main 26 1
INSERTIONS
3269896.343091
Percent of failed inserts: 0.000000
Total inserts: 63753417

QUERIES
Negative queries: 11241313.049951 /sec
Error rate: 0.000000
Positive queries: 5784638.906902 /sec
Error rate: 0.000000

REMOVALS
Removals: 3719529.748754 /sec
Number of failed removals: 0
Percent of failed removals: 0.000000
Negative queries after removals: 24142069.168804 /sec
Error rate: 0.000000
Positive queries after removals: 12307129.761754 /sec
Error rate: 0.000000

$ numactl -N 1 -m 1 ./main 26 2
INSERTIONS
5530393.533658
Percent of failed inserts: 0.000000
Total inserts: 63753417

QUERIES
Negative queries: 22931525.994402 /sec
Error rate: 0.000000
False negative query
Segmentation fault (core dumped)

$ numactl -N 1 -m 1 ./main 26 4
INSERTIONS
8419470.173530
Percent of failed inserts: 0.000000
Total inserts: 63753417

QUERIES
Negative queries: 42938471.121069 /sec
Error rate: 0.000000
False negative query
```

**Comment by badrishc** [comment]
Can you try using the code in branch cc-lmhc? We haven't merged that yet but some bugs are fixed there.  Also tagging @kkanellis who had been working on CC recently.

**Comment by prashantpandey** [comment]
Hi @badrishc , 

I tried the `cc-lmhc` branch and still seeing a seg fault while querying for items that are inserted. Is there documentation to understand the CC API? 
I have written this benchmark by looking at other benchmarks and tests in the CC directory. 

Is this the right way to perform inserts using multiple threads? Because queries work when using a single thread. 
```
  auto callback = [](IAsyncContext* ctxt, Status result) {
    assert(result == Status::Ok);
  };

  table->StartSession();
  for(uint64_t i = start; i < start + n; ++i) {
    UpsertContext context{ v[i].first, v[i].second };
    table->Upsert(context, callback, 1);
  }
  table->CompletePending(true);
  table->StopSession();
}
```

**Comment by badrishc** [comment]
We have a detailed benchmark program here: https://github.com/microsoft/FASTER/blob/master/cc/benchmark-dir/benchmark.cc

Does that not work for you?

**Comment by prashantpandey** [comment]
Yes, `benchamark.cc` works on the master branch. And I have tried to write my own drive code looking at the `benchmark.cc`. 
But there's probably something missing in my driver code. 

From what I understand, to perform multi-threaded inserts, you start a session and then perform upserts. Every thread then performs completePending and then stop the session. 

Is there documentation to understand what these API calls mean? I would appreciate any help to understand what's missing from my driver code that I have pasted in the initial comment. 

Thanks!

**Comment by badrishc** [comment]
Upon a brief, comparison, you seem to be missing the periodic thread refresh in the do_query loop. Threads need to call refresh for the epoch periodically. See benchmark.cc for example, and our research paper for details w.r.t. epoch protection.

```cs
      if(idx % kRefreshInterval == 0) {
        store->Refresh();
        if(idx % kCompletePendingInterval == 0) {
          store->CompletePending(false);
        }
      }
```

**Comment by prashantpandey** [comment]
Hi @badrishc , I tried this. It is still giving me seg fault when I am using 4 threads.

**Comment by badrishc** [comment]
I cannot run your code as it seems to be working only on non-Windows. You can try to debug and put breakpoints to see what is the source of the crash.
